---
- name: Fetch APOD data
  hosts: localhost
  tasks:
    - name: Fetch APOD for a specific date
      alta3.apod_tools.apod:
        api_key: DEMO_KEY
        date: "2024-11-20"
      register: apod_result

    - name: Display full APOD data
      debug:
        var: apod_result

    - name: Display only the image URL
      debug:
        msg: "Image URL: {{ apod_result.apod_data[0].hdurl }}"

